import { formatFileSize } from "../services/api";

const EvidenceReport = ({ analysisData, isOrgMode }) => {
  const { result, confidence, file, fileHash, timestamp } = analysisData;

  const generateReport = () => {
    const reportContent = `
DEEPFAKE DETECTION EVIDENCE REPORT
=====================================

ANALYSIS SUMMARY
----------------
Detection Result: ${result}
Confidence Level: ${confidence}%
Analysis Date: ${timestamp.toLocaleString()}
Report Generated: ${new Date().toLocaleString()}

FILE INFORMATION
----------------
File Name: ${file.name}
File Size: ${formatFileSize(file.size)}
File Type: ${file.type}
SHA-256 Hash: ${fileHash}

DETECTION DETAILS
-----------------
Detection Method: AI-based analysis using MobileNetV2 and MTCNN
Face Detection: MTCNN (Multi-task Cascaded Convolutional Networks)
Classification Model: MobileNetV2 with transfer learning
Analysis Mode: ${isOrgMode ? "Organization" : "Individual"}

INTERPRETATION
--------------
${result === "FAKE"
        ? "This video has been identified as potentially manipulated or synthetic content (deepfake). The AI model detected patterns consistent with artificial generation or manipulation."
        : result === "REAL"
          ? "This video appears to be authentic based on AI analysis. No significant manipulation artifacts were detected."
          : "The analysis was inconclusive. This may be due to video quality, lack of detectable faces, or technical limitations."
      }

RECOMMENDED ACTIONS
-------------------
${result === "FAKE"
        ? "1. Do not share or forward this content\n2. Preserve the original file as evidence\n3. Report to appropriate authorities\n4. Document the source and distribution\n5. Consider legal consultation"
        : "Verify the source and context of this video. If concerns persist, seek expert analysis."
      }

LEGAL DISCLAIMER
----------------
This report is generated by an AI-based detection system and should be used as guidance only, not as definitive proof. The accuracy of deepfake detection technology is continually evolving. For legal or critical decisions, consult with qualified experts and legal professionals.

This analysis was performed using Industry 5.0 compliant AI systems with human-centric design principles, emphasizing transparency, ethics, and trustworthiness.

PLATFORM INFORMATION
--------------------
Platform: Deepfake Detection & Response Platform
Technology: MobileNetV2, MTCNN, TensorFlow
Compliance: Industry 5.0 Standards
Privacy: No video data is permanently stored

=====================================
END OF REPORT
    `;

    // Create and download the report
    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Deepfake_Evidence_Report_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    alert(
      "Evidence report downloaded successfully. This report can be used for legal or organizational purposes.",
    );
  };

  return (
    <div className="evidence-report">
      <h3>Evidence Documentation</h3>
      <p className="report-description">
        Generate a professional report suitable for legal or organizational use
      </p>

      <div className="report-preview">
        <h4>Report will include:</h4>
        <ul className="report-contents">
          <li>Detection result and confidence score</li>
          <li>File information and SHA-256 hash</li>
          <li>Analysis timestamp and methodology</li>
          <li>Technical details and AI model information</li>
          <li>Recommended actions based on results</li>
          <li>Legal disclaimers and limitations</li>
        </ul>
      </div>

      <button className="generate-report-btn" onClick={generateReport}>
        📥 Download Evidence Report (TXT)
      </button>

      <div className="report-info">
        <small>
          Report includes: Detection result, confidence score, timestamp, file
          hash, and AI analysis disclaimer
        </small>
      </div>
    </div>
  );
};

export default EvidenceReport;
